### PR TITLE
v0.1.3

### PR DESCRIPTION
**Pull request by erogol**
# 🐸 v0.1.3

### 🐞Bug Fixes 
- Fix Tacotron stopnet training 

    Models trained after v0.1 had the problem that the stopnet was not trained. It caused models not to generate audio
    at evaluation and inference time.

- Fix `test_run` at training. (👑 @WeberJulian)

    In training :frog: TTS would skip the `test_run` and not generate test audio samples. Now it is fixed :). 

### 💾 Code updates
- Refactoring in `compute_embeddings.py` for efficiency and compatibility with the latest speaker encoder. (👑 @Edresson)

### 🚀 Model releases

- New Fullband-MelGAN model for Throsten German dataset. (👑 @thorstenMueller)

### CODE REVIEW

**Comment by mbarnig** [comment]
I installed this version to run some tests:
```   
Traceback (most recent call last):
  File "TTS/server/server.py", line 10, in <module>
    from flask import Flask, render_template, request, send_file
ModuleNotFoundError: No module named 'flask'
```

**Comment by thorstenMueller** [comment]
Hi @mbarnig .
According to https://github.com/coqui-ai/TTS/releases the new version has not been released yet.

**Comment by mbarnig** [comment]
@thorstenMueller : I know, I installed the dev branch. I think the purpose of the present comment  #674 is to get some early reactions before the release of the new version.

**Comment by erogol** [comment]
@mbarnig make sure you followed installation instructions. https://tts.readthedocs.io/en/latest/installation.html

**Comment by mbarnig** [comment]
@erogol : my fault. I was using the ancient command `pip install -e .` to install from source.

With 
```  
make system-deps
make install
```   

the script `python3 TTS/server/server.py` works without error.
In the future I will always check if the documentation has been changed before raising an issue.
Thanks for your quick response.

**Pull request merged**
