### PR TITLE
Adds support for precomputing conditioning latents to xtts for repeated inference on the same reference wavs for significant performance gains.

### PR DESCRIPTION
**Pull request by Iamgoofball**
Accidentally includes #2951 because I was lazy.

To use:
```
xtts = TTS("tts_models/multilingual/multi-dataset/xtts_v1", gpu=True)
xtts.synthesizer.tts_model.precompute_conditioning_latents("./path_to_wavs")

...

xtts.tts_to_file(
	text, 
	file_path="./path_to_output.wav", 
	speaker_wav="./xtts_ref_wavs/ref_speaker.wav", 
	language="en"
	precomputed_latents = True)

```

During benchmarking of the inference stack I found that like 2/3rds of the inference time was precomputation of the GPT latents. This is bad when you're working with fixed reference audio.

Without precomputed latents:
cmd_IhDhKtsHX7
With precomputed latents:
cmd_osc7WHG6vw

### CODE REVIEW

**Comment by skshadan** [comment]
pls provide full code.

**Comment by Iamgoofball** [comment]
this is the full code for this feature

**Comment by skshadan** [comment]
I used it still my inference time is same:(

**Comment by Iamgoofball** [comment]
i recommend doing some local benchmarking

**Comment by skshadan** [comment]
locally it is taking too much time:((

**Comment by skshadan** [comment]
image

**Comment by PranjalyaDS** [comment]
I have noticed that the latent computation is the longest during the first run, and the subsequent latent computations are taking time in a miniscule format, even if different reference audio files are used. I am not sure of the reason, the most obvious could be that the GPT and Diffusion latent generators are not lazy loaded, most probably?

**Pull request closed without merging**
