### PR TITLE
Introducing CLI revamp [WIP]

### PR DESCRIPTION
**Pull request by p0p4k**
I found TTS command line interface to be **slightly**  _un-intuitive_ ; be it typing complete model names OR re-loading models for every "--text" run even on the same model. On top of it, typing `--"parameter" "value"` seems so outdated. So, just to spice some things up, introducing a better and _modern_ CLI. 

image
image

- It is a WIP.
- Based on [python-inquirer](https://github.com/magmax/python-inquirer) package.
- My plan is to add all the features from existing CLI (with the help of synthesize.py).
- Supports holding the loaded model in memory to avoid re-loading it again unless "tts restarted".
image
- Supports changing speaker_idx and other multi-speaker params for the same loaded model without re-loading it.
- Added tqdm progress bar for model downloads based on feature request #1530 .
image
- Added model info support
image

- Gonna update the description as I add more features.
- Please comment if you have any new features in your mind.

### **Known bugs :** 
- arrow keys do not work for windows. current fix: Use num-pad arrow keys instead (num lock OFF). 
proper fix:The python-inquirer repo has a [PR](https://github.com/magmax/python-readchar/pull/71) for windows fix, waiting for merge.

### CODE REVIEW

**Comment by p0p4k** [comment]
On side note, I have even changed requirements.txt :  I have tested below config on python=3.10, pytorch=1.11, torchaudio=0.11.0 and works well with no errors. _Due to recent bump in numpy errors while installing TTS, I believe we need to rectify this ASAP. I might need some help with testing this configuration._ Thanks.
```
# core deps
numpy==1.22.4
numba==0.55.2
#deps for CLI
inquirer
```

**Comment by Cube707** [comment]
another FYI: I am now a contributer on `readchar` and was able to merge the fixes. Since the new `v3.0.6` the arrow keys should be properly supported on windows.

Also a new Version `v4.0.0` is currently in pre-releaes. It change quite a bit about the libary so maybe consier it in your development (or even give feedback if you find bugs in it..)

**Comment by erogol** [comment]
@p0p4k do you plan to continue this PR or should I leave it closed?

**Comment by p0p4k** [comment]
10/08/2022 : Closing now. Will open when I get some free time.

**Pull request closed without merging**
