### PR TITLE
Resample script from fork

### PR DESCRIPTION
**Pull request by WeberJulian**
Since it seems that many of us have made a script in local to resample a dataset I figured it would be good to have one on the repo.

This one is multithreaded, uses librosa to resample the wav files and can either resample inplace or create a copy of the dataset's directory.

### CODE REVIEW

**Comment by WeberJulian** [comment]
I closed the previous one since the commits I pushed wouln't show up here.
@SanjaESC I used distutils as you suggested and @erogol I added a test.
I also fixed a few linter errors and a mistake I made on a previous PR for the french cleaners.

**Comment by WeberJulian** [comment]
I think that is all. Can you think of anything to add/change ?

**Comment by erogol** [comment]
I merged this but somehow it still stays hanging. It is part of the new dev branch.

**Comment by WeberJulian** [comment]
Ok fine thx. That's weird because I had to reopen another PR from the fork of coqui-TTS to see the commits appear here but apparently it wasn't enough...

**Pull request closed without merging**
