### PR TITLE
New Tokenizer API

### PR DESCRIPTION
**Pull request by erogol**
- Tokenizer API

    Tokenizer API is defined by the TTSTokenizer class. It is intended to provide all the text processing functionalities to a `tts` model. New tokenizers can also be added by subclassing the TTSTokenizer class.

- Phonemizer API

    Phonemizer API is defined by the BasePhonemizer class and implemented by the ESpeak and Gruut wrappers, ZH_CH, 
    JP_JA phonemizers. New phonemizers can be added by implementing the BasePhonemizer class.

- BaseCharacters 

    BaseCharacters class provides an API to define the model vocabulary and provide the dictionary to map characters to 
    token IDs and back. There are two pre-defined classes inheriting from BaseCharacters. IPAPhonemes and Graphemes that respectively define the IPA phoneme character set for models using phonemes and grapheme set for models using raw characters.

- Punctuations class

    Punctuations class to strip out punctuations and restore them when needed.

- Language specific text normalization routines under `TTS.tts.utils.text` 

    Under `TTS.tts.utils.text` there are folders for each language to accommodate the text normalization routines that
    are designed for the language. 

- GlowTTS recipe and model using the new API 

    Other models are not compatible with the new API currently.

## TODO:

- [x] Add Tokenizer tests
- [x] Add Punctuation tests
- [x] Add Phonemizer tests
- [x] Add Characters tests
- [ ] Update rest of 🐸TTS for the new APIs

### CODE REVIEW

**Comment by synesthesiam** [comment]
I'll take a look this weekend, @erogol :+1:

**Comment by synesthesiam** [comment]
Should the Punctuation restore add in a separator? I noticed in the `gruut_wrapper.py` sample that the `|` is missing after the punctuation:

```
h|ɛ|l|o|ʊ| h|a|ʊ, ɑ|ɹ| j|u| t|ə|d|e|ɪ?
```

This doesn't matter when `separator=""` by default, but may cause issues otherwise.

**Comment by erogol** [comment]
separator does not cause an error but just for aesthetics since before converting to token IDs all the separators are removed. 

But yes in the best case separator should also separate punctuations after restore. The issue is cause by the difference between ESpeak and Gruut separators.

**Comment by thorstenMueller** [comment]
Still relevant.

**Comment by erogol** [comment]
This is already merged after rebasing

**Pull request closed without merging**
