### PR TITLE
Update distribute.py

### PR DESCRIPTION
**Pull request by astricks**
Simple fix to make distributed training work with python runner file.

### CODE REVIEW

**Comment by astricks** [comment]
Using runner.py script with distributed training results in an error. Stacktrace below.

Traceback (most recent call last):                                                                                                                                                           
  File "runner_glow.py", line 94, in <module>                                                                                                                                                
    trainer = Trainer(args, config, output_path)                                                                                                                                             
  File "/home/arvind/code/TTS/TTS/trainer.py", line 150, in __init__                                                                                                                         
    self.use_cuda, self.num_gpus = setup_torch_training_env(True, cudnn_benchmark)                                                                                                           
  File "/home/arvind/code/TTS/TTS/utils/trainer_utils.py", line 17, in setup_torch_training_env                                                                                              
Traceback (most recent call last):                                                                                                                                                           
  File "runner_glow.py", line 94, in <module>                                                                                                                                                
    trainer = Trainer(args, config, output_path)                                                                             
  File "/home/arvind/code/TTS/TTS/trainer.py", line 150, in __init__                                                    
    self.use_cuda, self.num_gpus = setup_torch_training_env(True, cudnn_benchmark)                  
  File "/home/arvind/code/TTS/TTS/utils/trainer_utils.py", line 17, in setup_torch_training_env
    f" [!] {num_gpus} active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`."                                                     
RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.                                                       
    f" [!] {num_gpus} active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`."                                                     
RuntimeError:  [!] 2 active GPUs. Define the target GPU by `CUDA_VISIBLE_DEVICES`. For multi-gpu training use `TTS/bin/distribute.py`.

**Comment by astricks** [comment]
Reported earlier in this discussion : https://github.com/coqui-ai/TTS/discussions/649

**Comment by astricks** [comment]
The exception seen here is raised by this commit which encourages using distributed.py for multi-GPU training.
https://github.com/coqui-ai/TTS/commit/a05b234080bbf87db1499d63778e81564bd55319

**Comment by erogol** [comment]
I think it is not a good fix since if you call 

```bash
CUDA_VISIBLE_DEVICES="0, 1, 3" python TTS/bin/distribute.py ...
```
if will try to use GPUs 0, 1, and 2 (not 3)

**Comment by astricks** [comment]
> I think it is not a good fix since if you call
> 
> ```shell
> CUDA_VISIBLE_DEVICES="0, 1, 3" python TTS/bin/distribute.py ...
> ```
> 
> if will try to use GPUs 0, 1, and 2 (not 3)

You're right @erogol, sorry for the hasty PR. I updated the patch and tested it locally.

**Comment by astricks** [comment]
Now to fix the tests.

**Review by erogol — APPROVED** [review]

**Comment by erogol** [comment]
Apparently, this does not solve the distributed training :( #707

**Pull request merged**
