### PR TITLE
[DO NOT MERGE | IGNORE] fixed PE

### PR DESCRIPTION
**Pull request by p0p4k**
rewrite (1000**(i/channels)) as exp(log(1000**(i/channels)) = exp((i/channels)*(log(1000))) == exp(i * (log(1000)/channels)) then The minus sign comes in the edited code because it is in denominator.

image
image
The 'dmodel' in image is 'channels' in our code.
Also, did we always forget to invert when multiplying the `div_term`  ?? 😮 
Although, we do divide in wavegrad.py 😌 
(see [wavegrad.py](https://github.com/p0p4k/TTS/blob/e5731fe0d1a33f6fc5f96f68aed2a819f3adf0b9/TTS/vocoder/layers/wavegrad.py#L34-L35))

lastly, optimization :
 
image
image

### CODE REVIEW

**Comment by p0p4k** [comment]
PR notes :

1. style test failures are related to lines that **this** PR _does not_ modify.
2. zoo-test failures (if any) are due to zip file not downloading (usual occurrence when mass zoo-testing models, fixes itself after re-test).

**Comment by erogol** [comment]
style checks are about the files you modified. This might help https://github.com/coqui-ai/TTS/blob/dev/CONTRIBUTING.md

**Review by p0p4k — COMMENTED** [review]
style fix

**Comment by p0p4k** [comment]
@erogol fixed style.

**Pull request closed without merging**
