### PR TITLE
Fix test inferences not happening during training

### PR DESCRIPTION
**Pull request by serg06**
I noticed test inferences weren't happening during training. I think this line is the issue. [Logic copied from here.](https://github.com/coqui-ai/TTS/blob/d245b5d48f01cdaf45479b7f924b8a74b6c58b97/TTS/bin/train_tacotron.py#L524)

### CODE REVIEW

**Comment by serg06** [comment]
Fixed unrelated issue that was causing CI test to break.

**Comment by erogol** [comment]
do you plan to fix the CI issues?  @serg06

**Comment by serg06** [comment]
@erogol I'll run it this evening and see if I can do that.

**Comment by erogol** [comment]
I guess @WeberJulian  is on this too

**Comment by serg06** [comment]
Closing since @WeberJulian did a much better job

**Pull request closed without merging**
