### PR TITLE
server: also listen to ipv6

### PR DESCRIPTION
**Pull request by Mic92**
The [::] address will listen to both ipv4/ipv6 addresses.

### CODE REVIEW

**Comment by erogol** [comment]
do you have a point er for that? I checked here but no mention https://flask.palletsprojects.com/en/master/api/#flask.Flask.run

**Comment by Mic92** [comment]
"::" is the ipv6 equivalent of ipv4's "0.0.0.0" but also accepts ipv4 addresses. However as I just found out this does not work on Windows... https://stackoverflow.com/questions/57881991/python-flask-dual-stack-on-windows-ipv4-and-ipv6

**Comment by mweinelt** [comment]
Also only if the linux distro defaults to `net.ipv6.bindv6only=0`, thought most do.

**Comment by Mic92** [comment]
The issue is that people try to connect to `localhost`, which can also yield `::1` instead of `127.0.0.1` as loopback adress in which case connection can fail.

**Comment by erogol** [comment]
how about if we just take an ```host ``` argument and let people decide?

**Comment by Mic92** [comment]
That would also make sense but is orthogonal since this is about the default as well.
@supersandro just confirmed that `::` actually works as intended on windows too.

**Comment by erogol** [comment]
Then I merge 👍 !!

**Pull request merged**
