### PR TITLE
Fix distribute.py and DDP training

### PR DESCRIPTION
**Pull request by erogol**

### CODE REVIEW

**Comment by agrinh** [comment]
@erogol I realize you're perhaps not done yet, but one thought:

Currently you're accessing a few methods using `self.model.module` in the trainer since `DDP` "hides" the methods you're using. AFAIK this can be a bit problematic if the method modifies or tries to access tensors (not sure if any of your current uses does). But issues like that are scary because they might be super difficult to debug and "fail" silently. It also requires a lot of if checks to see if the model has been wrapped with `DDP` or not.

How about breaking out the actual model definitions into separate `nn.Module`'s that only define `forward` (which should contain the current code in `model.forward` and `model.inference` but switching depending on if `self.training` is True or not.  This would mean having the training code (all other methods) elsewhere. Not sure where best to put the remaining functions, but if you put them all together in a class and gave it as another input to the trainer that would be pretty similar to pytorch lightnings `LightningModule`. I think this would also make code-reuse a bit easier.

```python
class Tacotron2(nn.Module):
    """Defines the forward pass."""

    def forward(self, ...):
        if self.training:
            # Current content in model.forward
            ...
        else:
            # Current content in model.inference, could share code with the other case
            ...
```

**Comment by erogol** [comment]
@agrinh you are right this much if-else looks stupid. But I don't get what you mean about `.module` and editing the tensors. Could you maybe give a code sample?

**Comment by agrinh** [comment]
Sure. Basically, all I'm suggesting is moving the model definition and forward pass into a separate class, and keep all other methods in the current model classes (`BaseModel` and forward) somewhere else.

Not sure where is easiest.  One alternative is to keep the existing model classes around, but the naming would be terrible:



```python
class Tacotron2(nn.Module):
    """Move the model into a regular nn.Module."""

    def forward(self, ...):
        if self.training:
            ... # Current content in model.forward
        else:
            ... # Current content in model.inference, could share code with the other case


class Tacotron2Interface(BaseTacotron):
    """Model interface."""
    
    def __init__(self, ...):
        self.model = Tacotron2(...)
        ...

    def train_step(self, ...):
        ...
        outputs = self.model(inputs)
        ...

    # Remains as those currently in the Tacotron2 model
    def get_train_dataloader(self, ...): ...
    def eval_step(self, ...): ...
    def train_log(self, ...): ...
    def eval_log(self, ...): ...


class Trainer:

    def __init__(self, model, ...):
        ...
        self.interface = Tacotron2Interface(...)
        if should_init_ddp:
            self.interface.model = DDP(self.interface.model)
        ...
        # No need to check for self.interface.model.module etc,
        # since the model only ever does the forward pass

    def train_epoch(self):
         ...
         self.model.train()
        for i, *batch in enumerate(dataloader):
            ...
            self.interface.train_step(*batch)
            ...

    ...
```

Another option would be to subclass the trainer and have a specific trainer for each model.

```python
class Tacotron2(nn.Module):
    ...  # Like above

class Trainer:
    """Same purpose as current trainer, but assumes training only defines `forward`.
    """

    def __init__(self, model, ...):
        ...
        self.model = model
        if should_init_ddp:
            self.model = DDP(self.model)
        ...

    @abstractmethod
    def train_step(self, batch):
        pass

    @abstractmethod
    def get_train_dataloader(self, ...):
        pass

    def train_epoch(self):
         ...
         self.model.train()
        for i, batch in enumerate(dataloader):
            ...
            self.train_step(batch)
            ...

    ...


class Tacotron2Trainer(Trainer):
    """Defines how to train Tacotron2.
    """
    def __init__(self, ...):
        ...
        super().__init__(model=Tacotron2(...))

    def train_step(self, ...):
        ...
        outputs = self.model(inputs)
        ...

    def get_train_dataloader(self, ...): ...
    def eval_step(self, ...): ...
    def train_log(self, ...): ...
    def eval_log(self, ...): ...
    ...
```

**Comment by erogol** [comment]
@agrinh thx for the snippets. I get what you suggest as a solution, but I don't get the argument you made about the Tensors in DDP and calling `.module`. 

Specifically here 

`AFAIK this can be a bit problematic if the method modifies or tries to access tensors (not sure if any of your current uses does). But issues like that are scary because they might be super difficult to debug and "fail" silently. It also requires a lot of if checks to see if the model has been wrapped with DDP or not.`

**Comment by agrinh** [comment]
@erogol Ah, gotcha. I don't know all that DDP does, but afaik DDP does some magic stuff and it might be dangerous to interact directly with the model. See e.g. this discussion: https://discuss.pytorch.org/t/custom-methods-in-distributeddataparallel/77114

**Pull request merged**
