### PR TITLE
added-custom-duration-for-vits

### PR DESCRIPTION
**Pull request by p0p4k**
- added a self explanatory vits phoneme duration changer.
- it can work for any model that uses duration predictor actually.
- notebook shows example for a single sentence, but can be extended to multiple sentences, will add more examples and notes with detailed explanations if users request for it.

### CODE REVIEW

**Comment by p0p4k** [comment]
@erogol hello, hope you having a good day! The checks are failing cause of premium coqui studio models, nothing else. Thank you!

**Comment by erogol** [comment]
Hey thanks for the PR. Can you some tests for the intended usage of the change?

**Comment by fkwlqm** [comment]
@erogol There is no change in the main body of the code. This notebook is just kind of a tutorial for extracting durations and modifying them as well as mixing multiple speaker embeddings.

**Comment by p0p4k** [comment]
> @erogol There is no change in the main body of the code. This notebook is just kind of a tutorial for extracting durations and modifying them as well as mixing multiple speaker embeddings.

That is my another GitHub account by the way 😄

**Comment by erogol** [comment]
I think this would make good content but I'd rather keep it separate. Notebooks are not ready to test and they create more annoyance than help after a while when there are compatibility issues. 

Maybe you can create a nice blog post with that?

**Comment by p0p4k** [comment]
Okay, nice blog post on its way. Soon.

**Comment by kexul** [comment]
Hi @p0p4k , may I ask where is the blog? Many thanks! I'd like to implement something similar in tortoise tts, is that possible?

**Comment by p0p4k** [comment]
@kexul the notebooks are self explanatory. If any doubts, shoot me a dm on discord (p0p4k)

**Pull request closed without merging**
