### PR TITLE
Update chinese phonemizer and add test case.

### PR DESCRIPTION
**Pull request by 46319943**
As stated in Issue https://github.com/coqui-ai/TTS/issues/1766#issue-1312752316, the splitting of Chinese words is removed.
In addition to that, the judgment of whether it is pinyin or not and the test cases for Chinese were added.

### CODE REVIEW

**Comment by erogol** [comment]
@46319943 thanks for the ✨PR✨

Can you try the Chinese model in the zoo with these changes to see if it breaks anything?

**Comment by 46319943** [comment]
@erogol Hi, I apologize for the delayed response.

I'm not quite sure what zoo is referring to, I think it might be the `tts_models/zh-CN/baker/tacotron2-DDC-GST` that appears in `list_models` ?

Unfortunately, I did not retrain the model due to time and data constraints.

However, I have trained the VITS model with another Chinese dataset after modification, and the result seems to be quite good. I'm currently up to 200K steps and I'm able to generate clear results, but I'm still having some problems with intonation.

**Comment by erogol** [comment]
@46319943 thanks for the update

> I'm not quite sure what zoo is referring to, I think it might be the tts_models/zh-CN/baker/tacotron2-DDC-GST that appears in list_models ?

Yeah exactly. That model should be okay with these changes. Or we can maybe update your VITS model using these changes.

**Comment by erogol** [comment]
@46319943 have you had a chance to check ``` tts_models/zh-CN/baker/tacotron2-DDC-GST``` with the new phonemizer?

**Comment by 46319943** [comment]
Not yet.
The baker dataset is not an open source dataset and requires payment to use. I do not have access to the original dataset.
Additionally, I do not currently have the GPU computing resources to train a new model. The GPU I used to train the model was leased.

In the future, if I have the latest GPU, I will train on the new dataset.

I apologize for not being able to train the new model with the changes.

**Comment by 46319943** [comment]
I have now finally had time to review this issue.

I think adding another phonemizer for Chinese might be ambiguous because they actually do the same thing, I just removed the unnecessary word splitting process and refined the process of determining whether it is pinyin or not.

Or should I add a recipe trained on the Chinese dataset?

**Comment by erogol** [comment]
> I think adding another phonemizer for Chinese might be ambiguous because they actually do the same thing

I think there is no other way to be backward compatible at the moment. 

> Or should I add a recipe trained on the Chinese dataset?

Yeah, it would be awesome.

**Pull request closed without merging**
