### PR TITLE
Datasets downloaders

### PR DESCRIPTION
**Pull request by loganhart420**
Just adding a function to download datasets from kaggle as well as adding libri tts, mailabs, tweb, and throsten datasets.

### CODE REVIEW

**Comment by erogol** [comment]
Can you rebase the latest dev to get rid of my commits?

**Comment by loganhart420** [comment]
I'm pretty sure that make style test will always fail because I've only gotten it to pass without an error code when I put the kaggle import at the top of the file, but that won't work because as soon as you use import kaggle it checks for the json file and will raise an error if you do not have it, so if someone wanted to download anything they would have to generate that file, so if someone just wanted to download the ljspeech dataset, they couldnt unless they have a kaggle account and have generated that file. not really sure how to get passed that test while keeping the import kaggle statement in the try block

**Comment by erogol** [comment]
You can add `# pylint disable=import-outside-toplevel` to silence pylint when there is no other way

You also need to rebase to the dev to get rid of the CLA issues. Your base branch is outdated.

**Comment by loganhart420** [comment]
theres something wrong with my local branch and I've tried everything I can think of but it constantly rejects my rebase push so I'm just going to close this and make a new clone and just make a new PR after I fix all my local changes

**Pull request closed without merging**
