### PR TITLE
Notebook with glow-tts training on LJspeech dataset for Italian

### PR DESCRIPTION
**Pull request by Nikav7**
@s1nayak
@FenNlay

### CODE REVIEW

**Comment by Nikav7** [comment]
@ZhengkunMei

**Comment by FenNlay** [comment]
The instructions are clear. It goes wrong were it said it would. The given instructions to get it to work do not help, sadly. It is, however, known by the author. It is said in the last block that it does not work as expected.

**Comment by ZhengkunMei** [comment]
First of alL, I must say this is a really amazing work contains lots of details and instruction, I just to follow the instruction and code in colab then I can run it easily.  The first notebook works well, I find it is interesting and try different text and get the wav file. The second and third notebook are also great, but some error occurs, like in the notebook 2 the first audio works well but I follow the instruction and get some error, the final sound is just a sound, not word(as the author has mentioned). About the third part, the author seems will countinue to work on it. Overall it is a great job and the author put her effort in it and get the expected result.

**Comment by ZhengkunMei** [comment]
So, based on the comment I have made, I recommand a grade of 9/10 for nica's work @S1nayak

**Comment by FenNlay** [comment]
After trying the notebooks several times, and some back and forth for clarifications (not through the comments) I could sense that the author put a lot of effort in the code and knows what is causing the error, just not yet how to fix it. The grade i would give is an 8/10

**Pull request closed without merging**
