### PR TITLE
feat: updated capacitron recipes and lr fix

### PR DESCRIPTION
**Pull request by a-froghyar**
- updated the recipes activating more losses for more stable training
- re-enabling guided attention loss
- fixed a bug in the capacitron optimizer: correct lr is now fetched for logging

### CODE REVIEW

**Comment by a-froghyar** [comment]
PR still WIP

**Comment by a-froghyar** [comment]
Update: recipes are working and the results are a lot more stable. I've trained a new model with `C=150` that I'd be happy to make available to update the current model that's less stable. cc @WeberJulian 

Screenshot 2022-07-11 at 13 47 00

**Comment by erogol** [comment]
Nice improvement 🚀. 

Is there more coming or I just merge this ✨PR✨?

**Comment by erogol** [comment]
@a-froghyar sure send it away!

**Pull request merged**
