### PR TITLE
mailabs formatter: back/forward slash in file path fix

### PR DESCRIPTION
**Pull request by freezerain**
Hello, I am training M-AI-Labs dataset and got the bug when mailabs formater from *TTS/tts/datasets/formatters.py* returning 0 items.

The problem is on the line 119:
```
if speaker_name_match is None:
            continue
```

The reason why *speaker_name* is not matching is because *regexr* on the line 100 can only match forwardslash while *glob* on the line 102 returning escaped back slashes, I believe because code is executed on the windows platform.
glob example return: 
```
['resampled_Ru\\by_book\\female\\hajdurova\\chetvero_nischih\\metadata.csv', ]
```
The most straightforward solution will be replace all "\\" with "/", this exactly what I am doing on the line 107 of this PR.

Alternative solutions:
-Arguable better will be adapt regexr to match backslash as well.
-It also possible to use *os.path.normpath(path)* across the whole method.
-On the line 108 we can add conditional execution of alternative regexr for situation when first didnt match anything. 

This is my first PR, please forgive me if I broke any rule/style/guideline, etc...

Have a nice day!

### CODE REVIEW

**Comment by erogol** [comment]
I think we can use ```os.path.sep``` instead of if...else

**Comment by freezerain** [comment]
True, we can build regexr with correct ``` os.path.sep```  symbol on method call, or we can get rid of any separator in the path completly for example splitting string to array.

I believe the core problem here is unconsistency because we using **regexr** to match **path** object as **string** object, idealy there should be a way to replace regexr with less fragile solution. 

However for me ```path.replace("\\", "/")``` is working good enough, even while its the ugliest of all options, my model is able to train in local as well as in google colab envirenment parsing google drive path to dataset without any problem.
Feel free to highjack this PR and find better solution that will be more robust and inline with quality of the rest of the project. 

I also found a lot of places where ``` path = root + "/some_suffix" ``` path building decision was made and not ``` path = os.path.join(root, "some_suffix")``` this leads to cases when you can get path like **root/MyFolder//some_suffix** and its need to be cleaned up from double separator, again because path treated as string. 😀

**Comment by erogol** [comment]
You can replace places with a separator with `os.path.sep`. It should quickly fix the issue for all the systems.

**Comment by freezerain** [comment]
I am usually not working with raw path data, I was trying to find a way to make this formatter safer, but after few hours cant find a way to do it without proper abstraction for each formatter type(each folder structure pattern), looks like lack of experience. Consider this arguments:
```
root: "MyCode/my_Samples" meta_data: None
root: "**/MyCode/my_Samples" meta_data: "*\\my_samples\\metadata.csv"
root: "./MyCode/../my_Samples/" meta_data: "./metadata.csv"
root: "..\\MyCode\\**\\my_Samples\\" meta_data: ["my_book/../metadata.csv", ]
```
While formatter is still fragile to inputs, I revisited each line to generalize path separator:
```
# before
os.path.join(root_path, "/**/metadata.csv")
# after
os.path.join(root_path, "**", "metadata.csv")
```
and changed **regexr.match(path)** approach to **path.split(separator)**:
```
folder_structure = os.path.normpath(csv_file).split(os.path.sep)
speaker_name = folder_structure[-3]
```

This PR can potentially brake someones old arguments, depends on how exactly people was getting around Windows OS bug in their projects (I assume they were just changing folder structure of dataset and using simplier formatter like ljspeech). 
Right now I am not planning to spend more time making path arguments safer, but I can wrap this code in separate formatter like "mailabs_win" or "mailabs_g" (g for generalized, not sure about naming) for compatibility with old workarounds.

I will be fine if team will reject this PR as its not a proper solution but a tiny bitsy more type-strict workaround.
Have a nice day!😺

**Comment by erogol** [comment]
@freezerain There are style issues that you can fix by running ```make style``.

It is useful to read https://github.com/coqui-ai/TTS/blob/dev/CONTRIBUTING.md

**Comment by freezerain** [comment]
Sorry, like I said this is my first PR, I was messing around with git submodules and polluted this PR with merge commits.
If you want to accept this PR how about I will create another fresh PR with only 1 commit for clean history?

**Comment by erogol** [comment]
that looks way better. Thx!

**Pull request merged**
