### PR TITLE
updated encoding for ljspeech, and added strip() to wav name

### PR DESCRIPTION
**Pull request by arif334**
`utf-8-sig` is proposed to avoid Byte Order Mark (BOM). 
Adding a strip() function when generating wav_file names is necessary if the text contains spaces around "|".

### CODE REVIEW

**Comment by erogol** [comment]
Please send PRs to the dev branch. 

I change the base now for you

**Comment by arif334** [comment]
> > utf-8-sig is proposed to avoid Byte Order Mark (BOM).
> 
> What does it mean in practice?

A special byte order mark (BOM) character is inserted at the beginning of utf-8 files by some programs/os. It causes problem reading the first word in the `metadata` (which is usually the `id` of the first sample). Using `encoding=utf-8-sig` will remove the BOM character if present.

**Comment by erogol** [comment]
Then it is a problem for custom datasets not for LJSpeech right? It only happens when you create your own metafile in certain OSs

**Comment by erogol** [comment]
I close this as a user can provide a custom formatter and it is not a real problem for the LJspeech dataset.

**Pull request closed without merging**
