### PR TITLE
Draft ONNX export for VITS

### PR DESCRIPTION
**Pull request by erogol**
~~Could not get it to output the variable length sequence. Dynamic shapes do not work for some reason. If anyone knows how, feel free to jump in.~~

Thanks to @manmay-nakhashi I fixed the issue. 

This is how it works 

```python 
from TTS.tts.models.vits import Vits
from TTS.tts.configs.vits_config import VitsConfig
from TTS.utils.audio.numpy_transforms import save_wav


config = VitsConfig()
config.load_json("config.json")
vits = Vits.init_from_config(config)
vits.load_checkpoint(config,  "model.pth")

vits.export_onnx()
vits.load_onnx("coqui_vits.onnx")

text = "This is a test"
text_inputs = np.asarray(
    vits.tokenizer.text_to_ids(text, language="en"),
    dtype=np.int64,
)[None, :]

audio = vits.inference_onnx(text_inputs)
print(audio.shape)

save_wav(wav=audio[0], path="coqui_vits.wav", sample_rate=config.audio.sample_rate)
```

### CODE REVIEW

**Comment by erogol** [comment]
@NeonBohdan can you give me sample code to reproduce?

**Comment by NeonBohdan** [comment]
@erogol sure
download [this model](https://github.com/coqui-ai/TTS/blob/dev/TTS/.models.json#L130)
and run [onnx_run.py.txt](https://github.com/coqui-ai/TTS/files/11431455/onnx_run.py.txt)


Got `AttributeError: 'Vits' object has no attribute 'disc'`

**Comment by erogol** [comment]
@NeonBohdan can you post the code here in the thread? I don't want to download a file that I don't know.

**Comment by NeonBohdan** [comment]
```
from TTS.tts.models.vits import Vits
from TTS.tts.configs.vits_config import VitsConfig
from TTS.utils.audio.numpy_transforms import save_wav

import numpy as np


config = VitsConfig()
config.load_json("model/config.json")
vits = Vits.init_from_config(config)
vits.load_checkpoint(config,  "model/model_file.pth")

vits.export_onnx()
vits.load_onnx("coqui_vits.onnx")

text = "This is a test"
text_inputs = np.asarray(
    vits.tokenizer.text_to_ids(text, language="en"),
    dtype=np.int64,
)[None, :]

audio = vits.inference_onnx(text_inputs)
print(audio.shape)

save_wav(wav=audio[0], path="coqui_vits.wav", sample_rate=config.audio.sample_rate)
```

**Comment by erogol** [comment]
I think your file has discriminator layers but config sets discriminator false. I could not reproduce the issue with default settings.

**Comment by NeonBohdan** [comment]
It's not my file, it's single speaker model trained by **Eren Gölge @erogol**, it available on TTS package model list and it weights 140MiB so discriminator weights removed
There is no possibility to convert it with this code

**Comment by NeonBohdan** [comment]
No problem, maybe the line **With [this model](https://github.com/coqui-ai/TTS/blob/dev/TTS/.models.json#L130)** was lost previously

**Comment by alessandropettenuzzo96** [comment]
Hi @erogol, thank you for this PR, it's saving me lot of time, could it be used also with Multi Speaker YourTTS?
It gives me an error executing `vits.export_onnx()`

`RuntimeError: Given groups=1, weight of size [196, 196, 1], expected input[1, 192, 100] to have 196 channels, but got 192 channels instead`

image

Thank you

**Comment by karelnagel** [comment]
> No problem, maybe the line **With [this model](https://github.com/coqui-ai/TTS/blob/dev/TTS/.models.json#L130)** was lost previously

Did you get it working? I have the same issue

**Comment by SystemPanic** [comment]
@erogol Onnx inference is 6-7 times slower than Pytorch due to exhaustive convolution search on cuDNN by default on OnnxRuntime. 

Can you change from `CUDAExecutionProvider` to `("CUDAExecutionProvider", {"cudnn_conv_algo_search": "DEFAULT"})` [here](https://github.com/coqui-ai/TTS/blob/4de797bb11736e329f89e2407d1001f1b9f47844/TTS/tts/models/vits.py#L1833)? 

With DEFAULT, OnnxRuntime performs ~20% better than VITS standard execution.

This performance issue is detailed on [https://github.com/microsoft/onnxruntime/issues/12880#issuecomment-1336147260](https://github.com/microsoft/onnxruntime/issues/12880#issuecomment-1336147260)

Thanks,

Javier.

**Comment by karelnagel** [comment]
> > No problem, maybe the line **With [this model](https://github.com/coqui-ai/TTS/blob/dev/TTS/.models.json#L130)** was lost previously
> 
> Did you get it working? I have the same issue

If anyone else is in this situation, then changing vits.py file on line 1771 to this:
```
# rollback values
_forward = self.forward
disc = None
if hasattr(self, 'disc'):
    disc = self.disc
training = self.training
```
worked for me (recommended in discord by Jpg#0419) . And also make sure that you have `onnx` installed (pip install onnx worked for me) and that the export file isn't named `onnx.py`.

**Comment by jpg-gamepad** [comment]
@erogol 
Hey thanks for the update! The ONNX exporter works great!

I am confused about how the text_to_ids function in your example works though.
What exact config settings does the function need to generate a token array (ex: [1,2,1,3,1,4,1,5]) from a text string?
Is it just <pad>, <eos> etc?

I'm looking through the code and the Vits Config Class extends like 4 other classes, and then gets overwritten by the config.json file, it's all very confusing.
I am running some experiments locally and just need a simple text_to_ids function to play with.

Any guidance or explanation would be helpful!

**Comment by SchweitzerGAO** [comment]
@alessandropettenuzzo96 hello, have you solved this? I encountered the same problem.

**Pull request merged**
