### PR TITLE
deleted a line that broke graves attention

### PR DESCRIPTION
**Pull request by a-froghyar**
`self.attention.init_win_idx()` was called during inference in `tacotron.py`. The `GravesAttention()` class does not have that method, and it broke inference for that case. For the case where the method is important - `OriginalAttention()`-, it is already called in `attentions.py` line 227. This also fixes https://github.com/coqui-ai/TTS/issues/383.

### CODE REVIEW

**Comment by erogol** [comment]
Breaks in what way? 

You can't remove that line since it breaks all the other attention methods.

**Comment by a-froghyar** [comment]
If you infer with Graves, it throws a no attribute error. the method `init_win_idx()` is only used in `OriginalAttention()` and is already called in the method `init_states()` of the OriginalAttention class.

**Comment by erogol** [comment]
You are right. It is already called in `init_states`. 

Can you also do the same for Tacotron2? And rebase the current `dev` please.

**Comment by a-froghyar** [comment]
yes, on it

**Comment by erogol** [comment]
Also, you need to `git rebase dev`. `models.yml` does not exist anymore.

**Comment by a-froghyar** [comment]
I did but it said all up to date, let me check again

**Comment by a-froghyar** [comment]
Should be fine now, sorry

**Comment by a-froghyar** [comment]
Give me a few hours and I'll fix the PR

**Comment by a-froghyar** [comment]
@erogol sorry for all the commits, I can start a new PR if it's a bit too cluttered, lmk

**Comment by erogol** [comment]
Yes would be better if you can squash some of the commits

**Pull request closed without merging**
