### PR TITLE
Add `download_model` option to TTS CLI

### PR DESCRIPTION
**Pull request by owahltinez**
This PR allows users to pre-download voice and vocoder models, which comes very handy in order to create Docker images (or VMs) that don't require connectivity to produce outputs.

### CODE REVIEW

**Comment by erogol** [comment]
So you just want to download a model without running inference? Is this the case?

**Comment by erogol** [comment]
Maybe it is more useful to have a separate command for downloading models that you can also define the download path as you like. How about this ?

**Comment by owahltinez** [comment]
Yes, the goal is to make sure everything is ready before synthesizing any text. I tried running `tts --text ...` during the Docker build process but that fails so I figured a separate argument made more sense.

If I create a separate command, how would I be able to call it using the `tts` binary?

**Comment by erogol** [comment]
we don't have to call tts. we can define a new command.

**Comment by owahltinez** [comment]
So you are proposing creating a new file under the `TTS/bin` folder, and adding a new [entrypoint](https://github.com/coqui-ai/TTS/blob/main/setup.py#L102)? Should it be named something like `tts-download`, or do you expect that it can grow into other miscellaneous utilities?

**Comment by erogol** [comment]
Yes, I propose to add a new entry-point like `tts-download`. I think keeping `tts` only for inference is good.

**Pull request closed without merging**
