### PR TITLE
Fix GST during inference (Tacotron2)

### PR DESCRIPTION
**Pull request by george-roussos**
This has been written a bit hastily (and it is a Friday, so even worse 😎), but here is a proposal on how to fix GST during inference (at least with Tacotron2).

Right now, GST is supposed to be grabbed through an argument (`--gst_style`) when calling `synthesize.py`. However, foregoing that right now this is not working (`args.gst_style` is not passed to `tts()`), this does not solve the case when we want to condition on a manual set of tokens and it is a dictionary. I propose we remove the CL argument and grab the value from the `config.json` instead. This way, we respect the way the GST class is setup and I also think it makes sense; check for a dictionary, then check for a wav, then fall-over to a zero Tensor.

If you have any alternatives, or comments, or suggestions (totally welcome!) you can let me know. If you would like to approve this, I can try and write some tests. 🙂

### CODE REVIEW

**Comment by george-roussos** [comment]
Hi, I changed reading the .wav file from the CL now. Please tell me if it looks okay. 🙂

**Comment by erogol** [comment]
can you rebase the dev to get rid of the style check error

**Comment by george-roussos** [comment]
Hi, sorry for the delay. Hopefully it is okay now.

**Comment by george-roussos** [comment]
Hi, I had a thought that it would be nice if there was support for a scaling factor when using a .wav file to do the GST conditioning. If that is an interesting idea, I can look into it.

**Comment by erogol** [comment]
Sounds good to me. But how about having it as a separate PR

**Comment by george-roussos** [comment]
Awesome, I will try to make it happen! Yeah, let's have a separate one about that

**Comment by erogol** [comment]
I'll merge this with the next version.

**Comment by erogol** [comment]
I just rebased this and squash-merged locally to the dev. I close it here. Thx for the ✨ PR ✨

**Pull request closed without merging**
