### PR TITLE
fix package versions

### PR DESCRIPTION
**Pull request by WeberJulian**

### CODE REVIEW

**Comment by akx** [comment]
I don't think it's a great idea to lock every version down to patch version level... I'm noticing my PRs are fervently trying to compile `scikit-learn` from scratch, it might be a better idea to just figure out why that is and fix that alone?

**Comment by WeberJulian** [comment]
@akx I've lowered the versions constrained using the `*` operator, but fixing has two main advantages: 1- the CI/install stop breaking without apparent reason because of an external package release. 2- Stricter versions makes the install significantly faster because it makes the task of the solver easier. What's your reasoning about not fixing the versions? Security concerns?

**Comment by akx** [comment]
If one was to try and use TTS as a library/dependency with tightly narrowed versions, they might easily end up in a situation where their other dependencies cause an unresolvable situation.

If TTS is never imagined to be used as a library (or a dependency for any other project at large) then it's not a concern.

**Comment by akx** [comment]
Also, it might be a good idea to think about making more of the per-model dependencies extras but that's probably out of scope for this PR.

**Pull request merged**
