### PR TITLE
Configurable verbose output

### PR DESCRIPTION
**Pull request by alexiri**
When using TTS as a library, sometimes the extra output is undesirable. This allows you to disable it.

### CODE REVIEW

**Comment by alexiri** [comment]
Still relevant.

**Comment by alexiri** [comment]
Still relevant

**Comment by erogol** [comment]
Looks like the inference tests did not pass. Logs are offline but maybe you can check locally what is wrong

**Comment by alexiri** [comment]
Still relevant.

**Comment by alexiri** [comment]
Still relevant. Is this project still maintained??

**Comment by jp-x-g** [comment]
@alexiri Coqui itself shut down some time at the beginning of January ( https://twitter.com/_josh_meyer_/status/1742522906041635166 ); the guy says in this that "Coqui TTS is on Github. Do something awesome with it!" so this seems to imply that someone was put in charge of the repository who was capable of maintaining it or at least accepting PRs to fix stuff. But I got on the Discord and it sounds like nobody really knows what the deal is supposed to be. Very sad if true, because this is a pretty decent project and the only one I've been able to get to work straightforwardly on my computer.

**Comment by alexiri** [comment]
Thanks @jp-x-g, I missed that. I guess that probably answers my question, then... :(

**Comment by davidmartinrius** [comment]
I have created a fork of TTS, incorporating all the valid pending pull requests. You can find it at https://github.com/davidmartinrius/TTS/

**Comment by eginhard** [comment]
In our fork we've now switched uses of `print` to use standard Python logging, allowing for configurable output: https://github.com/idiap/coqui-ai-TTS

**Pull request closed without merging**
