### PR TITLE
Trainer API 

### PR DESCRIPTION
**Pull request by erogol**
## Trainer API
A unified **trainer API** in place of the separate training scripts defined for each model. 

The plan is to define 4 trainers for 4 model categories.

1. `tts` models -> `train_tts.py`
2. `vocoder` models -> 'train_vocoder.py`
3. GAN based `vocoder` models. -> 'train_gan_vocoder.py`
4. `speaker_encoder` models. -> `train_speaker_encoder.py`

First I started to implement `TrainerTTS` with the following API.

```python
class TrainerTTS:
    use_cuda, num_gpus = setup_torch_training_env(True, False)

    def __init__(self,
                 args,
                 config,
                 c_logger,
                 tb_logger,
                 model=None,
                 output_path=None):
        ...

    def init_model(self):
        """Initialize the model by the config."""
        ...

    def init_optimizer(self, model):
        """Initialize the optimizer by the config parameters."""
        ...

    def init_character_processor(self):
        """Inititalize the character processor TBD"""
        ...

    def init_speaker_manager(self, restore_path: str = "", out_path: str = ""):
        """Initialize the speaker manager."""
        ...

    def init_scheduler(self, config, optimizer):
        """Initialize th LR scheduler. """
        ...

    def init_criterion(self):
        """Initialize the criterion."""
        return setup_loss(self.config)

    def restore_model(self,
                      config,
                      restore_path,
                      model,
                      optimizer,
                      scaler=None):
        """Restore the model from a pretrained model."""
        ...

    def _setup_loader(self, r, ap, is_eval, data_items, verbose, speaker_mapping):
        """Setup the dataloader."""
        ...

    def setup_train_dataloader(self, r, ap, data_items, verbose,
                               speaker_mapping):
        """Setup the dataloader for training."""
        ...

    def setup_eval_dataloder(self, r, ap, data_items, verbose,
                             speaker_mapping):
        """Setup the dataloader for evaluation."""
        ...

    def format_batch(self, batch):
        """Format the next batch of instances for the target model."""
        ...

    def train_step(self, batch, batch_n_steps, step, loader_start_time):
        """Train the model for a single forward and backward pass."""
        ...

    def train_epoch(self):
        """Train the model for an epoch."""
        ...

    def eval_step(self, batch, step):
        """Evaluate the model on a single batch of samples."""
        ...

    def eval_epoch(self):
        """Evaluate the model on the whole evaluation sampels.""" 
        ...

    def test_run(self, ):
        """Test the model on test sentences from the config."""
        ...

    def _get_cond_inputs(self):
        """Setup conditional inputs for testing. (e.g. x_vector, speaker_id)"""
        ...

    def fit(self):
        """Fit the model calling training, evaluation and testing functions."""
        ...

    def save_best_model(self):
        """Save the model if the loss is better than the previous best model."""
        ...

    def on_epoch_start(self):
        """Callback on epoch's start."""
        ...

    def on_epoch_end(self):
        """Callback on epoch's end."""
        ...

    def on_step_start(self):
        ...

    def on_step_end(self):
        ...

```

## Model API
This PR also presents important changes in the **model API** too. 

Every model will have the following structure. 

```python
class TTSModel(nn.Module):
    def __init__(self,):
    """initialize layers, variables and model parameter."""
        ...

    def forward(self):
    """Forward pass for training."""
        ...
        return outputs_dict

    def inference(self):
    """Forward pass for inference."""
        ...
        return outputs_dict

    def train_step(self, batch, criterion):
    """A Single training pass for the model. It takes a batch of instances and
    computes the loss and returns loss_dict and the model outputs.
    """
        ...
        return outputs_dict, loss_dict

    def train_log(self, ap, batch, outputs):
    """Visualizations and special logs to be projected to the Logger in use.
    """
        ...
        return figures_dict, train_audios

    def eval_step(self, batch, critetion):
    """A single evaluation pass for the model. It takes a batch of instances and
    computed the loss and returns loss_dict and the model outputs.

    It is in general very similar to the `train_step`.
    """
        ...
        return outputs_dict, loss_dict

    def eval_log(self, ap, batch, outputs):
    """Similar to the `train_log` but for evaluation."""
        ...
        return figures_dict, eval_audios

    def load_checkpoint(self, config, checkpoint_path, eval=False):
    """Load a pretrained model and make it ready for inference"""
        ...
```

### CODE REVIEW

**Comment by thorstenMueller** [comment]
Wow. That seems to be a big update.

**Comment by agrinh** [comment]
This looks pretty similar to PyTorch lightning. Why not go with that instead for this purpose? Would help you take care of logging, distributed training, some gpu optimization etc with minimal additional effort.

**Comment by erogol** [comment]
@agrinh good point. Maybe at a later time, we can consider PL  as a replacement or an alternative but I don't want to depend on an external library at the core of the project.

**Review by Edresson — APPROVED** [review]
Great restructuring :). I believe that now with the restructuring it's easier to add a new model and even support other modules (like GST, VAE)

**Comment by erogol** [comment]
@Edresson  good to hear that, The next step is to implement model abstractions for tts, vocoder, and speaker encoders for a clear exposition of the expected model APIs. Feel free to share proposals on that.

**Review by SanjaESC — COMMENTED** [review]
Looking good at first view  :+1: 
Should allow easier integration of new models and grant a better overview.

**Pull request merged**
