### PR TITLE
Japanese phonemizer that converts alphabets, symbols and numbers to words 

### PR DESCRIPTION
**Pull request by kaiidams**
This PR implements Japanese phonemizer that converts alphabets, symbols and numbers to words.

### CODE REVIEW

**Comment by erogol** [comment]
@kaiidams thx for the ✨PR✨. Do you plan to sign the CLA?

**Comment by kaiidams** [comment]
> @kaiidams thx for the ✨PR✨. Do you plan to sign the CLA?
@erogol Signed. Thank you!

**Comment by erogol** [comment]
can you rebase the dev branch and update the PR? 

We accept ✨ PRs✨  only to the dev branch 

This might help for the next PR https://github.com/coqui-ai/TTS/blob/main/CONTRIBUTING.md

**Comment by kaiidams** [comment]
Thanks, @erogol ! Rebased the change.

**Pull request merged**
