### PR TITLE
Capacitron

### PR DESCRIPTION
**Pull request by a-froghyar**
______________________________________________________________________________________________________
_Disclaimer_

@Edresson and @WeberJulian have asked me to open a PR with my newly implemented model, Capacitron. There are still some things to clean up and some fixes to do, however I'm opening this PR already for the discussion around it. Contributions for the list below are welcome, however I'll be slow in the next 10 days with checking them. I have just merged the new `dev` branch into this branch with the new Coqpit refactor among others and I haven't had the chance to try to run the training yet. I've implemented this model as my master thesis and I'm currently still training different models for the thesis, so I won't have too much capacity (hehe) to experiment in the next month.
______________________________________________________________________________________________________

This PR implements a new model into 🐸 TTS based on the [Capacitron](https://google.github.io/tacotron/publications/capacitron/) model from Google. It's a partial implementation of the models detailed in the paper, hierarchical latent embeddings are still to be done - this is a TODO for later. If you'd like to get an idea what the model does and how it works, [here's a post I did a few weeks ago](https://github.com/coqui-ai/TTS/discussions/455). Audio samples to follow shortly.

**Phonemes**

I haven't followed the entire discussion about the phoneme issue, however I'm aware that because of license issues, espeak needed to be dropped. @Edresson mentioned that I could try to train the model with graphemes as well, however I haven't had time to do this yet. According to the paper, however, Capacitron does need phoneme inputs to work. 

**TODOs** (List is still to be updated):

- [x] Implement Coqpit config instead of `capacitron_blizzad.json`
- [x] Fix changes coming from formatting
- [x] Fix capacitron multispeaker training -- (HInt: `tacotron_abstract.py`)
- [x] Refactor the parameter splitting in `train_tacotron.py` and `training.py`
- [ ] Create test for `capacitron_layers.py`
- [ ] Fix tests
- [ ] Refactor `capacitron_eval.py` into a notebook
- [ ] Fix https://github.com/a-froghyar/Capacitron/issues/8
- [x] Fix https://github.com/a-froghyar/Capacitron/issues/4
- [x] Fix https://github.com/a-froghyar/Capacitron/issues/5

**To Discuss**

- Some of the losses that are normally activated in Tacotron are deactivated in Capacitron - during my experiments I stripped down the loss calculation to the bare minimum (which is already complicated enough) and I haven't experimented with turning them back on again since then
- DDC + Capacitron

### CODE REVIEW

**Comment by Edresson** [comment]
> _Disclaimer_
> 
> @Edresson and @WeberJulian have asked me to open a PR with my newly implemented model, Capacitron. There are still some things to clean up and some fixes to do, however I'm opening this PR already for the discussion around it. Contributions for the list below are welcome, however I'll be slow in the next 10 days with checking them. I have just merged the new `dev` branch into this branch with the new Coqpit refactor among others and I haven't had the chance to try to run the training yet. I've implemented this model as my master thesis and I'm currently still training different models for the thesis, so I won't have too much capacity (hehe) to experiment in the next month.
> 
> This PR implements a new model into  TTS based on the [Capacitron](https://google.github.io/tacotron/publications/capacitron/) model from Google. It's a partial implementation of the models detailed in the paper, hierarchical latent embeddings are still to be done - this is a TODO for later. If you'd like to get an idea what the model does and how it works, [here's a post I did a few weeks ago](https://github.com/coqui-ai/TTS/discussions/455). Audio samples to follow shortly.
> 
> **Phonemes**
> 
> I haven't followed the entire discussion about the phoneme issue, however I'm aware that because of license issues, espeak needed to be dropped. @Edresson mentioned that I could try to train the model with graphemes as well, however I haven't had time to do this yet. According to the paper, however, Capacitron does need phoneme inputs to work.
> 
> **TODOs** (List is still to be updated):
> 
> * [ ]  Implement Coqpit config instead of `capacitron_blizzad.json`
> * [ ]  Fix changes coming from formatting
> * [ ]  Fix capacitron multispeaker training -- (HInt: `tacotron_abstract.py`)
> * [ ]  Refactor the parameter splitting in `train_tacotron.py` and `training.py`
> * [ ]  Create test for `capacitron_layers.py`
> * [ ]  Fix tests
> * [ ]  Refactor `capacitron_eval.py` into a notebook
> * [ ]  Fix [a-froghyar#4](https://github.com/a-froghyar/Capacitron/issues/4)
> 
> **To Discuss**
> 
> * Some of the losses that are normally activated in Tacotron are deactivated in Capacitron - during my experiments I stripped down the loss calculation to the bare minimum (which is already complicated enough) and I haven't experimented with turning them back on again since then
> * DDC + Capacitron

Thanks, @a-froghyar an excellent PR congratulations again :). I will help and fix the compatibility issues. I also intend to leave the VAE generic and implement support in Tacotron 2. I intend to add it as was done for GST.

**Comment by a-froghyar** [comment]
Thanks a lot! T2 integration sounds exciting, I'll definitely be on it with you.

**Comment by erogol** [comment]
Also be aware of the upcoming Trainer API. Maybe it is better for you to check it as you design your PR :sparkles: .

**Comment by a-froghyar** [comment]
Update:

@Edresson was kind enough to open a PR on the branch - https://github.com/a-froghyar/Capacitron/pull/6 -, this is being reviewed this week and will be pushed hopefully soon. The list on the top will be updated by the end of this week and the new Trainer API will also be taken into account.

**Comment by a-froghyar** [comment]
Little update: I'm finishing up my thesis in the next 2 months so activity here won't be too much in the meantime, however there is active development on the model/PR :)

**Comment by a-froghyar** [comment]
I'm submitting and presenting my thesis in the next weeks, the PR is still active.

**Comment by erogol** [comment]
@a-froghyar good luck!

**Comment by a-froghyar** [comment]
I'm done with the masters and I'll be working on this PR in the next week. @erogol @Edresson @WeberJulian could I post Qs here later? There seemed to have been loads of changes in the past 3 months so it'll take some time to reorganise things. :)

**Comment by a-froghyar** [comment]
OK, there's way too many conflicts - I'm actually going to restart the PR from a fresh dev branch. I'm gonna post the new PR here for follow-up!

**Pull request closed without merging**
