### PR TITLE
Dev pr2 : handle multi-speaker and GST in synthetizer class

### PR DESCRIPTION
**Pull request by kirianguiller**
Hi guys,

Here the second split of the PR I did earlier this week.

This new content is for handling multi speaker and GST inference in the Synthesizer class (that is used in server.py or in the google colab for Chinese that I mentioned in the first point). Now, you can pass the following two optional parameters to the Synthesizer.tts()  method : 
_speaker_json_key_ and _style_wav_ . _speaker_json_key_ is the name of the key of one of the speaker in the provided speakers.json . _style_wav_ is either a path to a wav file for GST style transfer, or is a dict containing the {"token1":0.25, "token2" -0.1, etc...}.  *The next step is to also give the user the possibility to directly provide the optional parameter _speaker_embedding_ that is a speaker embedding (as a numpy array or a list?) that will be passed to Tacotron at inference time.

The synthesizer class is now simplier to use, and we can see in this [google colab](https://colab.research.google.com/drive/1y2wQ0fp2ishZQVjSPp1dR8P_PLdxAvu_?usp=sharing) that this reduces the number of lines required for having working generation samples.

Thanks :)

### CODE REVIEW

**Comment by erogol** [comment]
Sorry for being slow. I'll check the PR definitely the latest tomorrow.

**Comment by kirianguiller** [comment]
No problem ! Just let me know if you have any requests for modification :)

**Comment by erogol** [comment]
I think the only immediate requirement is writing some testing code for the synthesizer. I'll write one for the current synthesizer in the dev branch then you can rebase and add more for multi-speaker and GST changes you made.

**Comment by erogol** [comment]
ok we already have ```test_synthesizer.py``` :)

Can you implement test cases for your changes - GST and multi-speaker?

**Comment by kirianguiller** [comment]
Yes ! I will implement this and push the changes at the beginning of next week :)

**Comment by erogol** [comment]
@kirianguiller any updates?

**Comment by kirianguiller** [comment]
> @kirianguiller any updates?

Yes sorry, quite busy weeks I had here. Thanks for reminding me though. I will implement the test for the code I added and work on the new conflicts.

**Comment by erogol** [comment]
@kirianguiller  I am also on this PR. Maybe better if you wait me to push my updates. I also rebased the latest dev. 

I'll ping you.

**Comment by kirianguiller** [comment]
Oh cool ! Thank you. I am waiting for your changes then :)

**Comment by erogol** [comment]
I close this for the sake of #441

**Pull request closed without merging**
