### PR TITLE
Update manage.py

### PR DESCRIPTION
**Pull request by Mkkrishnasai**
Issue at _set_model_item() function
While using fairseq model dataset & model variables are not set

### CODE REVIEW

**Comment by eginhard** [comment]
This is already fixed in [our fork](https://github.com/idiap/coqui-ai-TTS) (available via `pip install coqui-tts`). This repo is not updated anymore.

**Comment by manuel-84** [comment]
After trying this fix I get this error with TTS api

`ValueError:  [!] Model file not found in the output path
`

Code:
```
api = TTS("tts_models/lat/fairseq/vits")
api.tts_with_vc_to_file(
    text,
    speaker_wav="sample.wav",
    file_path="output.wav"
)
```

**Comment by eginhard** [comment]
@manuel-84 Can you try just running this:
```python
api = TTS("tts_models/lat/fairseq/vits")
api.tts_to_file(
    text,
    file_path="output.wav"
)
```

**Comment by manuel-84** [comment]
> @manuel-84 Can you try just running this:
> 
> ```python
> api = TTS("tts_models/lat/fairseq/vits")
> api.tts_to_file(
>     text,
>     file_path="output.wav"
> )
> ```

Same error... I will try with your repo

**Comment by eginhard** [comment]
@manuel-84 I just checked and I can use this model without errors. If it still doesn't work with the fork, try removing the `tts_models--lat--fairseq--vits/` folder, your download might have been incomplete.

**Comment by Mkkrishnasai** [comment]
@manuel-84 

```
api = TTS("tts_models/lat/fairseq/vits")
api.tts_with_vc_to_file(
    text,
    speaker_wav="sample.wav",
    file_path="output.wav"
)

```
`ValueError:  [!] Model file not found in the output path `

"api.tts_with_vc_to_file" is correct as your using "tts_models/lat/fairseq/vits" single language model with voice cloning support.

This could also be because of model download issue. 

if Darwin "~/Library/Application\ Support" delete the model and try again.
different for Windows or custom path.

**Comment by rose07** [comment]
https://tts.byylook.com/ai/text-to-speech

**Pull request closed without merging**
