### PR TITLE
Hifigan Vocoder

### PR DESCRIPTION
**Pull request by rishikksh20**

### CODE REVIEW

**Comment by erogol** [comment]
Any updates @rishikksh20 ?

**Comment by thorstenMueller** [comment]
I'm interested in HifiGAN too. Excited to do a training on my "Thorsten" dataset.

**Comment by rishikksh20** [comment]
@erogol Yes I have trained model on different configuration but not able to train successfully, I even copy paste original hifi-gan with exact settings and only use TTS data loader with pre-processing and yet result is same the audio is not understandable at all I think I need to go through TTS pre-processing thoroughly because I think I miss something there, also I have implemented l1 loss mentioned in hifigan paper and training on original hifigan architecture lets see how it's turnout. Also original hifigan takes a week to get trained so it takes time.

**Comment by erogol** [comment]
@rishikksh20 do you have a certain timeline on this? I try to plan the next release and see if you are up for it.

Feel free to tell if time is scarse, just asking for planing.

**Comment by rishikksh20** [comment]
@erogol it will finished within end of first week of April.

**Comment by rishikksh20** [comment]
@erogol One more think when I replaced TTS melspectrogram pre-processing with mine melspectrogram calculation it's working fine I think the problem is with pre-processing only.

**Comment by erogol** [comment]
I guess we can retire this as we merged HiFiGAN. Thanks, @rishikksh20  for initiating the work.

**Pull request closed without merging**
