### PR TITLE
Improve docsQA default questions

### PR DESCRIPTION
**Pull request by nomagick**
More on docsQA:

We figured out a set of better-answered questions.
Hope this improves some user experience.

You can also set the default questions to something else.

To ask more questions, preview: https://tts--preview-jina-ai.netlify.app/

### CODE REVIEW

**Comment by erogol** [comment]
Thanks for the update

Do you have a structured way to figure out these questions ?

**Comment by nan-wang** [comment]
> Do you have a structured way to figure out these questions ?
@erogol For the first-time cold starting, nope. The motivation of showing these question is to guide the users to ask questions instead of typing keywords. Therefore, it is a bit hard to automatically choose them. One feature we are building is to index the FAQ page and maybe the questions from there can serve as a better starting point. Plus, We are building a console so that you can have a better preview and choose the question. 

Furthermore, we plan to collect and cluster the frequently asked questions so that you can continuously add them to your FAQ page. Do you think this feature will be helpful?

**Comment by erogol** [comment]
Thanks for the reponse 

> Furthermore, we plan to collect and cluster the frequently asked questions so that you can continuously add them to your FAQ page. Do you think this feature will be helpful?

Definitely !

**Comment by nan-wang** [comment]
hey, @erogol, I am wondering whether we will merge this PR before next release?

**Comment by erogol** [comment]
will be merged with the next release.

**Pull request merged**
