### PR TITLE
Tortoise inference fix and fix zoo unit tests

### LINKED ISSUE #3005: [Bug]  Tortoise inference not functional
### Describe the bug

I can't seem to use tortoise `tts_models/en/multi-dataset/tortoise-v2`.

```
File ".../python3.10/site-packages/TTS/tts/layers/tortoise/tokenizer.py", line 24, in encode
    return self.tokenizer.encode(txt).ids
AttributeError: 'NoneType' object has no attribute 'encode'
```

### To Reproduce

```
tts --model_name  tts_models/en/multi-dataset/tortoise-v2 \
--text "This is an example." \
--out_path "output.wav" \
--progress_bar True
```

### Expected behavior

_No response_

### Logs

_No response_

### Environment

```shell
TTS == 0.17.5
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Edresson**
It fixes #3005 and added a inference unit test for tortoise inference.

### CODE REVIEW

**Comment by Lenos500** [comment]
> It fixes #3005 and added a inference unit test for tortoise inference.

Don't forget about XTTS the tokenizer.py in that model generates a voicebpetokenizer attribute error related to preprocess object

**Comment by Lenos500** [comment]
> > > It fixes #3005 and added a inference unit test for tortoise inference.
> > 
> > 
> > Don't forget about XTTS the tokenizer.py in that model generates a voicebpetokenizer attribute error related to preprocess object
> 
> Hi @Lenos500,
> 
> Sorry, but I dont get what you mean. Tortoise and XTTS have different tokenizers. XTTS inference is working fine to me.
> 
> Can you give a reproducible example, please?

It's a closed issue which I already posted about #3000

**Comment by Lenos500** [comment]
> > > It fixes #3005 and added a inference unit test for tortoise inference.
> > 
> > 
> > Don't forget about XTTS the tokenizer.py in that model generates a voicebpetokenizer attribute error related to preprocess object
> 
> Hi @Lenos500,
> 
> Sorry, but I dont get what you mean. Tortoise and XTTS have different tokenizers. XTTS inference is working fine to me.
> 
> Can you give a reproducible example, please?

Do you think the error I mentioned for xtts_v1 can be fixed while keeping it able to load on cpu? I'm not the only user suffering from the voicebpetokenizer error when running the model locally on a Linux machine be it Ubuntu or kali Linux

**Comment by Edresson** [comment]
> > > > It fixes #3005 and added a inference unit test for tortoise inference.
> > > 
> > > 
> > > Don't forget about XTTS the tokenizer.py in that model generates a voicebpetokenizer attribute error related to preprocess object
> > 
> > 
> > Hi @Lenos500,
> > Sorry, but I dont get what you mean. Tortoise and XTTS have different tokenizers. XTTS inference is working fine to me.
> > Can you give a reproducible example, please?
> 
> Do you think the error I mentioned for xtts_v1 can be fixed while keeping it able to load on cpu? I'm not the only user suffering from the voicebpetokenizer error when running the model locally on a Linux machine be it Ubuntu or kali Linux

Hi, 

Can you use the instructions on [docs](https://tts.readthedocs.io/en/dev/models/xtts.html) to do inference with xtts model, please?  
Using the latest :frog:  TTS version I was not able to replicate the issue that you mentioned. I was able to load and do inference in GPU and CPU with both TTS API and command line. If you are not able to load the model please open an issue with all the details including the env, TTS version, and others.

**Comment by Lenos500** [comment]
> > > > > It fixes #3005 and added a inference unit test for tortoise inference.
> > > > 
> > > > 
> > > > Don't forget about XTTS the tokenizer.py in that model generates a voicebpetokenizer attribute error related to 
preprocess object
> > > 
> > > 
> > > Hi @Lenos500,
> > > Sorry, but I dont get what you mean. Tortoise and XTTS have different tokenizers. XTTS inference is working fine to me.
> > > Can you give a reproducible example, please?
> > 
> > 
> > Do you think the error I mentioned for xtts_v1 can be fixed while keeping it able to load on cpu? I'm not the only user suffering from the voicebpetokenizer error when running the model locally on a Linux machine be it Ubuntu or kali Linux
> 
> Hi,
> 
> Can you use the instructions on [docs](https://tts.readthedocs.io/en/dev/models/xtts.html) to do inference with xtts model, please? Using the latest 🐸 TTS version I was not able to replicate the issue that you mentioned. I was able to load and do inference in GPU and CPU with both TTS API and command line. If you are not able to load the model please open an issue with all the details including the env, TTS version, and others.

It worked now, turned out I needed to put the vocab.json file in the same directory I'm using to load the model and its config. Even the documentation does not mention the vocab file in its instructions.

**Pull request merged**
