### PR TITLE
Tokenizer API (Rebased)

### PR DESCRIPTION
**Pull request by erogol**

### CODE REVIEW

**Comment by thorstenMueller** [comment]
@erogol do you have a time schedule for continue this topic? @domcross and i are training a german tts model and run into pronounciation problems using phonemes (regardless if `use_espeak` is set to true or false).

**Comment by erogol** [comment]
@thorstenMueller  we don't have a release date but working on it. 

There is no use_espeak anymore. Based on the language, it picks the right G2P backend. For the most, it picks the espeak-ng or espeak depending on the one installed in the system.

**Comment by erogol** [comment]
@thorstenMueller which backend do you use? I found a bug when  using espeak-ng

**Comment by thorstenMueller** [comment]
> @thorstenMueller which backend do you use? I found a bug when using espeak-ng

Espeak-ng  ;)

**Comment by erogol** [comment]
try switching to espeak for now

**Pull request closed without merging**
