### PR TITLE
Fixed some typos and grammar mistakes

### PR DESCRIPTION
**Pull request by undefdev**
I also made some changes when I thought it improves readability, or makes the text more idiomatic.
Feel free to adopt any changes you like.

### CODE REVIEW

**Comment by undefdev** [comment]
I think I agreed to the CLA, but I'm not sure if it worked.

**Comment by erogol** [comment]
Thx for the ✨PR✨ 

Can you merge this PR with your other PR? Also, you need to sign the CLA for me to merge it.

**Comment by undefdev** [comment]
Alright, everything should be in order now.

**Comment by erogol** [comment]
You also need to rebase to the latest dev to get rid of my commit above. 

(We don't take PRs for the main branch but the dev.)

**Comment by undefdev** [comment]
Ok, I rebased onto the dev branch.

**Comment by undefdev** [comment]
(Not sure what that changed though, tbh)

**Comment by erogol** [comment]
Just manually fixed these to get rid of the residual commit. Thanks for the flag.

**Pull request closed without merging**
