### PR TITLE
Fix bark model

### PR DESCRIPTION
**Pull request by ipeevski**

### CODE REVIEW

**Comment by AntonyZ89** [comment]
up

please, someone merge it (:

**Comment by davidmartinrius** [comment]
I have created a fork of TTS, incorporating all the valid pending pull requests. You can find it at https://github.com/davidmartinrius/TTS/

**Comment by irdan** [comment]
Adding this error message to make it easier for others to discover this issue via search

2, "_pickle.UnpicklingError: invalid"..., 48_pickle.UnpicklingError: invalid load key, '<'.

**Comment by eginhard** [comment]
I've merged this into [our fork](https://github.com/idiap/coqui-ai-TTS), thank you!

**Comment by namtacs** [comment]
up

**Pull request closed without merging**
