### PR TITLE
Adding neural HMM TTS Model

### PR DESCRIPTION
**Pull request by shivammehta25**
https://github.com/coqui-ai/TTS/pull/2271 Updated to a new model to avoid problems with model zoo and other test cases.

Neural HMM TTS (2021) is a parameter-efficient version and predecessor to OverFlow (28.6M vs 15.3M), it was the probabilistic spectrogram generation model which introduced neural HMMs into a TTS architecture in "Neural HMMs are all you need (for high-quality attention-free TTS)". Because of half the number of parameters the synthesis output quality is suboptimal (but comparable to Tacotron2 without Postnet) but it learns to speak with a lesser amount of data and is significantly faster than other attention-based methods. 
* Paper [arXiv](https://arxiv.org/abs/2108.13320)
* Paper [ICASSP 2022](https://ieeexplore.ieee.org/document/9746686)
* Demo: [Webpage](https://shivammehta25.github.io/Neural-HMM)

### CODE REVIEW

**Comment by shivammehta25** [comment]
@erogol All tts-test are raising a `ModuleImportFailure` error. I don't think it is because of this PR or is it?

**Comment by erogol** [comment]
I think it is about your system setup. Something is broken. We don't see it on the CI tests.

You should also rebase your code with v0.10.2 to make the tests pass the above.

**Comment by shivammehta25** [comment]
@erogol ` > Error: Bad zip file - https://github.com/coqui-ai/TTS/releases/download/v0.6.1_models/tts_models--en--vctk--vits.zip` I think this was just a CI error how do I retrigger the CI?

**Comment by erogol** [comment]
That is not PR relevant. It is just a network issue. I'll restart the test.

**Comment by erogol** [comment]
@shivammehta25 Thx again for the PR. I merge this. You might also want to add docs for your models for better visibility as in https://github.com/coqui-ai/TTS/tree/dev/docs/source/models

**Pull request merged**
